### ISSUE TITLE
Test testPanocMultipleRuns fails

### ISSUE THREAD

**Issue by alphaville** [kul-forbes/EmbeddedMPC#19]
The test fails because `p->gamma` has changed. 

Should we reset `gamma` between invocations for the algorithm?

By the way, why is the initial value of `gamma` set to `p->gamma = 5.4785;`?

**Comment by AjSat** [comment]
Yes, indeed the value the algorithm converges to depends on the initial value of gamma. So, I have reset the value of gamma as well as the LBFGS buffer and the issue is resolved. 

gamma was set to 5.4785 simply because one of the panoc tests required that value. I have now set it to 100 in panoc.c and separately initialized gamma to 5.4785 in the test function.
